# 1  How to use the ‘groupby()’ function in pandas

Welcome to this hands on about grouping data using pandas. This notebook presents the practical side of the concepts explained in the video. The dataset used in this notebook can be downloaded from [here](https://www.kaggle.com/datasets/subhaskumarray/netflixoriginals). This hands on covers the following topics:

• Split- Apply- Combine functionality

• Filtering the groups

• Data Transformation

Learners are expected to run this notebook on their own systems. Some of the output has not beenshown to keep the notebook precise.

# 1.1  Import pandas and load the data

The DataFrame here is named as movies_info. The downloaded dataset is saved in the present working directory.

In [1]:
pip install pandas

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pandas in c:\programdata\anaconda3\lib\site-packages (1.5.3)
Requirement already satisfied: python-dateutil>=2.8.1 in c:\programdata\anaconda3\lib\site-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\programdata\anaconda3\lib\site-packages (from pandas) (2022.7)
Requirement already satisfied: numpy>=1.21.0 in c:\programdata\anaconda3\lib\site-packages (from pandas) (1.24.3)
Requirement already satisfied: six>=1.5 in c:\programdata\anaconda3\lib\site-packages (from python-dateutil>=2.8.1->pandas) (1.16.0)
Note: you may need to restart the kernel to use updated packages.

In [2]:
import pandas as pd

In [3]:
movies_info = pd.read_csv('NetflixOriginals.csv', encoding='ISO-8859-1')

# 1.2  Understand the dataset

Let us begin by understanding the data using the commonly used methods.

In [4]:
movies_info.head()

,Title,Genre,Premiere,Runtime,IMDB Score,Language
0,Enter the Anime,Documentary,"August 5, 2019",58,2.5,English/Japanese
1,Dark Forces,Thriller,"August 21, 2020",81,2.6,Spanish
2,The App,Science fiction/Drama,"December 26, 2019",79,2.6,Italian
3,The Open House,Horror thriller,"January 19, 2018",94,3.2,English
4,Kaali Khuhi,Mystery,"October 30, 2020",90,3.4,Hindi

In [5]:
len(movies_info)

584

The dataset has 6 columns and 584 rows. The columns have features about movies such as theTitle, Genre, etc. Let us begin by forming groups from this data for further analysis.

# 1.3  Split

The first step is to split the dataset where grouping is done based on the values in a particular column.

# 1.3.1  Grouping data based on the value of a column

As we know that groupby() can form groups based on the value of a column in DataFrame. We can see this by forming groups based on Genre column. This grouping would provide information about the movies in each genre.

Find out how many movies of each genre exists in the DataFrame

In [6]:
grouped = movies_info.groupby('Genre')

Groups have been formed and stored in ‘grouped’ variable as a result of running the previous cell.We can see what groups have been formed by using .groups as shown below. Also, notice the alphabetical order of the groups obtained.

A snippet of the output has been shown below. (This is not the complete output).

{‘Action’: [5, 39, 50, 153, 220, 277, 372], ‘Action comedy’: [13, 61, 155, 205, 257], ‘Actionthriller’: [318], ‘Action-adventure’: [507], ‘Action-thriller’: [55, 315, 450], ‘Action/Comedy’: [99],‘Action/Science fiction’: [104], ‘Adventure’: [232, 337], ‘Adventure-romance’: [227], ‘Adven-ture/Comedy’: [122], ‘Aftershow / Interview’: [66, 407, 434, 439, 451, 528], ‘Animated musicalcomedy’: [366], ‘Animation’: [64, 253, 452, 453, 506], ‘Animation / Comedy’: [446],

In [7]:
grouped.groups

{'Action': [5, 39, 50, 153, 220, 277, 372], 'Action comedy': [13, 61, 155, 205, 257], 'Action thriller': [318], 'Action-adventure': [507], 'Action-thriller': [55, 315, 450], 'Action/Comedy': [99], 'Action/Science fiction': [104], 'Adventure': [232, 337], 'Adventure-romance': [227], 'Adventure/Comedy': [122], 'Aftershow / Interview': [66, 407, 434, 439, 451, 528], 'Animated musical comedy': [366], 'Animation': [64, 253, 452, 453, 506], 'Animation / Comedy': [446], 'Animation / Musicial': [309], 'Animation / Science Fiction': [537], 'Animation / Short': [325, 417, 513, 560], 'Animation/Christmas/Comedy/Adventure': [573], 'Animation/Comedy/Adventure': [314], 'Animation/Musical/Adventure': [306], 'Animation/Superhero': [51], 'Anime / Short': [40], 'Anime/Fantasy': [364], 'Anime/Science fiction': [323, 368], 'Anthology/Dark comedy': [543], 'Biographical/Comedy': [391], 'Biopic': [166, 207, 234, 239, 245, 255, 420, 449, 499], 'Black comedy': [123, 126], 'Christian musical': [141], 'Christmas comedy': [215], 'Christmas musical': [68], 'Christmas/Fantasy/Adventure/Comedy': [448], 'Comedy': [6, 9, 18, 22, 27, 28, 29, 33, 35, 47, 48, 54, 65, 69, 72, 73, 74, 75, 77, 83, 85, 96, 103, 110, 112, 119, 124, 125, 127, 138, 149, 158, 160, 167, 184, 221, 229, 231, 249, 261, 271, 278, 327, 342, 377, 397, 399, 447, 492], 'Comedy / Musical': [107, 430], 'Comedy horror': [150], 'Comedy mystery': [212], 'Comedy-drama': [81, 128, 134, 161, 176, 203, 248, 285, 305, 311, 385, 423, 431, 518], 'Comedy/Fantasy/Family': [94], 'Comedy/Horror': [185], 'Coming-of-age comedy-drama': [489], 'Concert Film': [293, 525, 532, 557, 578, 579], 'Crime drama': [116, 230, 233, 287, 361, 429, 461, 491, 500, 508, 561], 'Crime thriller': [280], 'Dance comedy': [243], 'Dark comedy': [145, 181], 'Documentary': [0, 10, 15, 20, 30, 36, 80, 111, 140, 151, 152, 199, 202, 223, 228, 259, 260, 263, 275, 286, 290, 292, 295, 301, 303, 304, 308, 310, 312, 316, 320, 324, 326, 329, 334, 339, 351, 353, 355, 356, 357, 359, 363, 367, 370, 371, 373, 375, 378, 384, 387, 392, 393, 394, 396, 400, 401, 402, 403, 404, 410, 412, 414, 415, 416, 419, 424, 425, 426, 427, 432, 433, 435, 436, 437, 440, 441, 442, 443, 444, 445, 455, 456, 458, 459, 460, 462, 463, 464, 465, 466, 468, 469, 471, 472, 473, 476, 479, 480, 482, ...], 'Drama': [11, 37, 41, 53, 56, 70, 82, 87, 92, 93, 97, 102, 148, 164, 165, 168, 169, 189, 191, 198, 208, 210, 211, 222, 224, 235, 236, 241, 246, 247, 258, 269, 273, 274, 276, 284, 291, 299, 307, 317, 322, 335, 336, 338, 343, 354, 365, 369, 374, 376, 381, 382, 383, 388, 389, 390, 405, 406, 408, 409, 411, 418, 438, 454, 470, 475, 477, 481, 488, 490, 493, 504, 549, 551, 559, 562, 565], 'Drama / Short': [345], 'Drama-Comedy': [487], 'Drama/Horror': [268], 'Family': [144, 225], 'Family film': [52, 266], 'Family/Christmas musical': [333], 'Family/Comedy-drama': [270], 'Fantasy': [186], 'Heist': [44], 'Heist film/Thriller': [7], 'Hidden-camera prank comedy': [346], 'Historical drama': [495], 'Historical-epic': [422], 'Horror': [31, 34, 46, 59, 71, 90, 101, 146, 348], 'Horror anthology': [16], 'Horror comedy': [139], 'Horror thriller': [3, 19, 331], 'Horror-thriller': [240, 265], 'Horror/Crime drama': [262], 'Making-of': [496, 558], 'Mentalism special': [457], 'Mockumentary': [174, 197], 'Musical': [108, 204], 'Musical / Short': [552], 'Musical comedy': [296, 330], 'Musical/Western/Fantasy': [8], 'Mystery': [4, 196], 'One-man show': [179, 467, 581], 'Political thriller': [17], 'Psychological horror': [195], 'Psychological thriller': [157, 347, 352, 474], 'Psychological thriller drama': [118], 'Romance': [132, 321, 344, 350, 421, 428], 'Romance drama': [32], 'Romantic comedy': [12, 26, 58, 67, 84, 91, 95, 105, 114, 121, 129, 131, 147, 156, 162, 163, 171, 173, 175, 177, 187, 188, 190, 200, 216, 217, 218, 238, 256, 264, 272, 289, 300, 319, 341, 349, 395, 478, 486], 'Romantic comedy-drama': [180], 'Romantic comedy/Holiday': [226], 'Romantic drama': [63, 135, 143, 302, 379], 'Romantic teen drama': [142], 'Romantic teenage drama': [106], 'Romantic thriller': [214], 'Satire': [178, 182], 'Science fiction': [78, 120, 136, 358], 'Science fiction adventure': [76], 'Science fiction thriller': [340], 'Science fiction/Action': [281], 'Science fiction/Drama': [2, 38, 283], 'Science fiction/Mystery': [115], 'Science fiction/Thriller': [170, 183, 209, 294], 'Sports film': [206], 'Sports-drama': [193, 250, 297], 'Spy thriller': [360, 362], 'Stop Motion': [244], ...}

The output is a dictionary which shows the results of grouping as a key value pair, where,

•key is the ‘Genre’ or the group name;

•value is a list of the row labels of the group members.

as shown in the below output snippet. The complete output has not been shown to keep this document precise.

You can also see how many groups have been obtained by using len() on the dictionary obtained above.

In [8]:
len(grouped.groups)

115

There are 115 groups formed. The number of groups formed should be equal to the number of unique values in the Genre column since each unique genre would form a group of its own.

In [9]:
movies_info['Genre'].nunique()

115

You can also see the size of each group by using .size(). This shows the number of movies belonging to each genre.

In [10]:
grouped.size()

Genre
Action              7
Action comedy       5
Action thriller     1
Action-adventure    1
Action-thriller     3
                   ..
War                 2
War drama           2
War-Comedy          1
Western             3
Zombie/Heist        1
Length: 115, dtype: int64

# 1.4  Grouping data based on the value of multiple columns

Groups can also be created by using multiple columns. ### Find out how many movies belonging to each language are there in each genre.

In [11]:
grouped_1 = movies_info.groupby(['Genre', 'Language'])

Task: Also try what happens when the order of columns is reversed when passing multiple column names to groupby().

Let us have a look at the results of grouping using .groups This will output all the groups formed as we saw in the previous case. Part of the output has been shown below:

{('Action', 'English'): [153, 220, 277, 372], ('Action', 'French'): [39, 50], ('Action', 'Hindi'): [5], ('Action comedy', 'English'): [61, 155, 205, 257], ('Action comedy', 'Malay'): [13], ('Action thriller', 'English'): [318], ('Action-adventure', 'English/Korean'): [507], ('Action-thriller', 'English'): [55, 315], ('Action-thriller', 'Indonesian'): [450],

In [15]:
grouped_1.groups

{('Action', 'English'): [153, 220, 277, 372], ('Action', 'French'): [39, 50], ('Action', 'Hindi'): [5], ('Action comedy', 'English'): [61, 155, 205, 257], ('Action comedy', 'Malay'): [13], ('Action thriller', 'English'): [318], ('Action-adventure', 'English/Korean'): [507], ('Action-thriller', 'English'): [55, 315], ('Action-thriller', 'Indonesian'): [450], ('Action/Comedy', 'English'): [99], ('Action/Science fiction', 'English'): [104], ('Adventure', 'English'): [232, 337], ('Adventure-romance', 'English'): [227], ('Adventure/Comedy', 'English'): [122], ('Aftershow / Interview', 'English'): [66, 407, 434, 439, 451, 528], ('Animated musical comedy', 'English'): [366], ('Animation', 'English'): [64, 253, 452, 453, 506], ('Animation / Comedy', 'English'): [446], ('Animation / Musicial', 'English'): [309], ('Animation / Science Fiction', 'English'): [537], ('Animation / Short', 'English'): [325, 417, 513, 560], ('Animation/Christmas/Comedy/Adventure', 'English'): [573], ('Animation/Comedy/Adventure', 'English'): [314], ('Animation/Musical/Adventure', 'English'): [306], ('Animation/Superhero', 'English'): [51], ('Anime / Short', 'English'): [40], ('Anime/Fantasy', 'Japanese'): [364], ('Anime/Science fiction', 'Japanese'): [323, 368], ('Anthology/Dark comedy', 'Hindi'): [543], ('Biographical/Comedy', 'English'): [391], ('Biopic', 'English'): [166, 207, 234, 239, 255, 420, 449, 499], ('Biopic', 'Italian'): [245], ('Black comedy', 'English'): [123], ('Black comedy', 'Spanish/Basque'): [126], ('Christian musical', 'English'): [141], ('Christmas comedy', 'English'): [215], ('Christmas musical', 'English'): [68], ('Christmas/Fantasy/Adventure/Comedy', 'English'): [448], ('Comedy', 'English'): [22, 27, 47, 48, 65, 69, 72, 73, 74, 75, 77, 83, 103, 119, 124, 125, 127, 138, 149, 158, 160, 167, 184, 221, 229, 231, 261, 342, 399, 492], ('Comedy', 'French'): [28, 85], ('Comedy', 'Hindi'): [9, 112, 327, 397], ('Comedy', 'Italian'): [29, 35, 447], ('Comedy', 'Korean'): [18], ('Comedy', 'Portuguese'): [33, 54, 110, 271, 278, 377], ('Comedy', 'Spanish'): [96], ('Comedy', 'Turkish'): [6, 249], ('Comedy / Musical', 'English'): [107, 430], ('Comedy horror', 'English'): [150], ('Comedy mystery', 'English'): [212], ('Comedy-drama', 'English'): [81, 134, 203, 285, 305, 385, 431, 518], ('Comedy-drama', 'Hindi'): [176, 423], ('Comedy-drama', 'Indonesian'): [248, 311], ('Comedy-drama', 'Marathi'): [161], ('Comedy-drama', 'Portuguese'): [128], ('Comedy/Fantasy/Family', 'English'): [94], ('Comedy/Horror', 'English'): [185], ('Coming-of-age comedy-drama', 'Spanish'): [489], ('Concert Film', 'English'): [293, 525, 532, 557, 578, 579], ('Crime drama', 'Dutch'): [461], ('Crime drama', 'English'): [116, 230, 429, 500, 561], ('Crime drama', 'English/Japanese'): [287], ('Crime drama', 'French'): [233], ('Crime drama', 'Hindi'): [491], ('Crime drama', 'Italian'): [508], ('Crime drama', 'Spanish'): [361], ('Crime thriller', 'English'): [280], ('Dance comedy', 'English'): [243], ('Dark comedy', 'English'): [145, 181], ('Documentary', 'Bengali'): [473], ('Documentary', 'English'): [10, 20, 80, 111, 140, 152, 199, 202, 223, 228, 259, 260, 275, 286, 290, 301, 303, 304, 308, 310, 312, 326, 329, 339, 351, 353, 355, 356, 357, 359, 363, 367, 370, 371, 373, 387, 393, 396, 401, 402, 403, 404, 414, 416, 424, 425, 426, 427, 432, 433, 435, 440, 441, 442, 443, 444, 445, 455, 456, 459, 460, 462, 464, 465, 466, 468, 469, 471, 472, 476, 479, 480, 482, 483, 484, 498, 501, 502, 503, 511, 517, 519, 520, 521, 522, 523, 526, 527, 529, 530, 531, 534, 535, 536, 538, 540, 541, 542, 544, 545, ...], ('Documentary', 'English/Arabic'): [512], ('Documentary', 'English/Hindi'): [485, 524], ('Documentary', 'English/Japanese'): [0], ('Documentary', 'English/Mandarin'): [394, 514], ('Documentary', 'English/Russian'): [515], ('Documentary', 'English/Spanish'): [30, 263, 295, 320, 510], ('Documentary', 'English/Swedish'): [334], ('Documentary', 'English/Ukranian/Russian'): [580], ('Documentary', 'French'): [36, 292, 324, 400, 412, 415], ('Documentary', 'Georgian'): [410], ('Documentary', 'Japanese'): [378], ('Documentary', 'Korean'): [533], ('Documentary', 'Portuguese'): [419, 494, 582], ('Documentary', 'Spanish'): [15, 384, 392, 436, 437, 458, 463, 575], ('Documentary', 'Spanish/Catalan'): [316], ('Documentary', 'Spanish/English'): [505], ('Documentary', 'Thai'): [151], ('Documentary', 'Thia/English'): [375], ('Drama', 'English'): [93, 148, 164, 165, 191, 198, 211, 222, 224, 247, 258, 269, 291, 299, 317, 322, 336, 369, 374, 376, 381, 389, 406, 409, 411, 418, 438, 454, 470, 475, 477, 488, 549, 562, 565], ('Drama', 'English/Taiwanese/Mandarin'): [343], ('Drama', 'Filipino'): [37], ('Drama', 'French'): [102, 307], ('Drama', 'German'): [189], ('Drama', 'Hindi'): [87, 97, 168, 169, 210, 241, 274, 335, 354, 365, 388, 405, 551], ('Drama', 'Indonesian'): [56, 236, 273], ('Drama', 'Italian'): [41, 82, 208, 408], ('Drama', 'Japanese'): [284], ('Drama', 'Khmer/English/French'): [481], ('Drama', 'Korean'): [11, 382], ('Drama', 'Marathi'): [70, 493], ...}

Let us find out the size of each group formed by using .size()

In [16]:
grouped_1.size()

Genre          Language
Action         English         4
               French          2
               Hindi           1
Action comedy  English         4
               Malay           1
                              ..
War drama      English/Akan    1
War-Comedy     English         1
Western        English         2
               Portuguese      1
Zombie/Heist   English         1
Length: 204, dtype: int64

# 1.5  Selecting a group and forming subsets of data

# 1.5.1  Form a subset of the dataset containing only comedy movies

From the groups formed above,any group may be selected by using .get_group() and passing the group name. For example, the groups formedby using genre ‘Comedy’ canbe obtained by running the below cell.

In [19]:
grouped.get_group('Comedy')

,Title,Genre,Premiere,Runtime,IMDB Score,Language
6,Leyla Everlasting,Comedy,"December 4, 2020",112,3.7,Turkish
9,Sardar Ka Grandson,Comedy,"May 18, 2021",139,4.1,Hindi
18,What Happened to Mr. Cha?,Comedy,"January 1, 2021",102,4.3,Korean
22,Sextuplets,Comedy,"August 16, 2019",99,4.4,English
27,Seriously Single,Comedy,"July 31, 2020",107,4.5,English
28,The Misadventures of Hedi and Cokeman,Comedy,"February 10, 2021",99,4.5,French
29,5 Star Christmas,Comedy,"December 7, 2018",95,4.6,Italian
33,Porta dos Fundos: The First Temptation of Christ,Comedy,"December 3, 2019",46,4.6,Portuguese
35,The Players,Comedy,"July 15, 2020",88,4.6,Italian
47,Take the 10,Comedy,"January 20, 2017",80,4.8,English
48,The Main Event,Comedy,"April 10, 2020",101,4.8,English
54,Airplane Mode,Comedy,"January 23, 2020",96,5.0,Portuguese
65,#REALITYHIGH,Comedy,"September 8, 2017",99,5.2,English
69,Father of the Year,Comedy,"July 20, 2018",94,5.2,English
72,Girlfriend's Day,Comedy,"February 14, 2017",70,5.2,English
73,Handsome: A Netflix Mystery Movie,Comedy,"May 5, 2017",81,5.2,English
74,Hubie Halloween,Comedy,"October 7, 2020",103,5.2,English
75,Ibiza,Comedy,"May 25, 2018",94,5.2,English
77,Sandy Wexler,Comedy,"April 14, 2017",131,5.2,English
83,The Week Of,Comedy,"April 27, 2018",116,5.2,English
85,Back to School,Comedy,"August 30, 2019",83,5.3,French
96,Despite Everything,Comedy,"May 3, 2019",78,5.4,Spanish
103,Naked,Comedy,"August 11, 2017",96,5.4,English
110,Get the Grift,Comedy,"April 28, 2021",94,5.5,Portuguese
112,House Arrest,Comedy,"November 15, 2019",104,5.5,Hindi
119,Step Sisters,Comedy,"January 19, 2018",108,5.5,English
124,Unicorn Store,Comedy,"April 5, 2019",92,5.5,English
125,Wine Country,Comedy,"May 10, 2019",103,5.5,English
127,Brahman Naman,Comedy,"July 7, 2016",95,5.6,English
138,The Sleepover,Comedy,"August 21, 2020",103,5.6,English
149,Lionheart,Comedy,"January 4, 2019",94,5.7,English
158,The Wrong Missy,Comedy,"May 13, 2020",90,5.7,English
160,Yes Day,Comedy,"March 12, 2021",86,5.7,English
167,Candy Jar,Comedy,"April 27, 2018",92,5.8,English
184,The After Party,Comedy,"August 24, 2018",89,5.8,English
221,Between Two Ferns: The Movie,Comedy,"September 20, 2019",82,6.1,English
229,Like Father,Comedy,"August 3, 2018",103,6.1,English
231,Otherhood,Comedy,"August 2, 2019",100,6.1,English
249,Have You Ever Seen Fireflies?,Comedy,"April 9, 2021",114,6.2,Turkish
261,Win It All,Comedy,"April 7, 2017",88,6.2,English
271,Get the Goat,Comedy,"March 18, 2021",97,6.3,Portuguese
278,Porta dos Fundos: The Last Hangover,Comedy,"December 21, 2018",44,6.3,Portuguese
327,Chopsticks,Comedy,"May 31, 2019",100,6.5,Hindi
342,The Incredible Jessica James,Comedy,"July 28, 2017",83,6.5,English
377,Just Another Christmas,Comedy,"December 3, 2020",101,6.7,Portuguese
397,Long Live Brij Mohan,Comedy,"August 3, 2018",105,6.8,Hindi
399,Death to 2020,Comedy,"December 27, 2020",70,6.8,English
447,Rose Island,Comedy,"December 9, 2020",117,7.0,Italian
492,The 40-Year-Old Version,Comedy,"October 9, 2020",124,7.2,English

The output will be a 49 row DataFrame consisting of all the columns which have the genre ‘Comedy’

# 1.6  Iterating through groups

To see all the groups formed as a result of groupby(), for loop can be used on the grouped data.The first group is shown below as an example. You would see 115 such groups. A sample output after one iteration has been shown below:

In [22]:
for name, group in grouped:
    print("Group Name:", name)
    print(group[['Title','Genre']],'\n')
    print('_____________________________End of group____________________________')

Group Name: Action
               Title   Genre
5              Drive  Action
39        Sentinelle  Action
50   Earth and Blood  Action
153      Point Blank  Action
220    6 Underground  Action
277            Polar  Action
372       Extraction  Action

_____________________________End of group____________________________
Group Name: Action comedy
                                         Title          Genre
13                          All Because of You  Action comedy
61                             Coffee & Kareem  Action comedy
155                                The Do-Over  Action comedy
205  True Memoirs of an International Assassin  Action comedy
257                       Spenser Confidential  Action comedy

_____________________________End of group____________________________
Group Name: Action thriller
        Title            Genre
318  Wheelman  Action thriller

_____________________________End of group____________________________
Group Name: Action-adventure
    Title             Genre
507  Okja  Action-adventure

_____________________________End of group____________________________
Group Name: Action-thriller
                      Title            Genre
55              How It Ends  Action-thriller
315         Triple Frontier  Action-thriller
450  The Night Comes for Us  Action-thriller

_____________________________End of group____________________________
Group Name: Action/Comedy
              Title          Genre
99  Game Over, Man!  Action/Comedy

_____________________________End of group____________________________
Group Name: Action/Science fiction
                Title                   Genre
104  Outside the Wire  Action/Science fiction

_____________________________End of group____________________________
Group Name: Adventure
                            Title      Genre
232         Pee-wee's Big Holiday  Adventure
337  Mowgli: Legend of the Jungle  Adventure

_____________________________End of group____________________________
Group Name: Adventure-romance
                   Title              Genre
227  Holiday in the Wild  Adventure-romance

_____________________________End of group____________________________
Group Name: Adventure/Comedy
                                     Title             Genre
122  The Legacy of a Whitetail Deer Hunter  Adventure/Comedy

_____________________________End of group____________________________
Group Name: Aftershow / Interview
                                                 Title                  Genre
66   American Factory: A Conversation with the Obamas   Aftershow / Interview
407           The Boys in the Band: Something Personal  Aftershow / Interview
434  I'm No Longer Here: A Discussion with Guillerm...  Aftershow / Interview
439  Ma Rainey's Black Bottom: A Legacy Brought to ...  Aftershow / Interview
451  13th: A Conversation with Oprah Winfrey & Ava ...  Aftershow / Interview
528                      The Irishman: In Conversation  Aftershow / Interview

_____________________________End of group____________________________
Group Name: Animated musical comedy
                      Title                    Genre
366  Arlo the Alligator Boy  Animated musical comedy

_____________________________End of group____________________________
Group Name: Animation
                                  Title      Genre
64               The Larva Island Movie  Animation
253  Octonauts & the Caves of Sac Actun  Animation
452                  Angela's Christmas  Animation
453             Angela's Christmas Wish  Animation
506  Octonauts & the Great Barrier Reef  Animation

_____________________________End of group____________________________
Group Name: Animation / Comedy
                                 Title               Genre
446  Rocko's Modern Life: Static Cling  Animation / Comedy

_____________________________End of group____________________________
Group Name: Animation / Musicial
                                       Title                 Genre
309  Sturgill Simpson Presents: Sound & Fury  Animation / Musicial

_____________________________End of group____________________________
Group Name: Animation / Science Fiction
                              Title                        Genre
537  Invader Zim: Enter the Florpus  Animation / Science Fiction

_____________________________End of group____________________________
Group Name: Animation / Short
                              Title              Genre
325                         Canvas   Animation / Short
417                Cops and Robbers  Animation / Short
513         Sitara: Let Girls Dream  Animation / Short
560  If Anything Happens I Love You  Animation / Short

_____________________________End of group____________________________
Group Name: Animation/Christmas/Comedy/Adventure
     Title                                 Genre
573  Klaus  Animation/Christmas/Comedy/Adventure

_____________________________End of group____________________________
Group Name: Animation/Comedy/Adventure
               Title                       Genre
314  The Willoughbys  Animation/Comedy/Adventure

_____________________________End of group____________________________
Group Name: Animation/Musical/Adventure
             Title                        Genre
306  Over the Moon  Animation/Musical/Adventure

_____________________________End of group____________________________
Group Name: Animation/Superhero
       Title                Genre
51  Fearless  Animation/Superhero

_____________________________End of group____________________________
Group Name: Anime / Short
          Title          Genre
40  Sol Levante  Anime / Short

_____________________________End of group____________________________
Group Name: Anime/Fantasy
              Title          Genre
364  A Whisker Away  Anime/Fantasy

_____________________________End of group____________________________
Group Name: Anime/Science fiction
                         Title                  Genre
323  Altered Carbon: Resleeved  Anime/Science fiction
368                     Blame!  Anime/Science fiction

_____________________________End of group____________________________
Group Name: Anthology/Dark comedy
    Title                  Genre
543  Ludo  Anthology/Dark comedy

_____________________________End of group____________________________
Group Name: Biographical/Comedy
                           Title                Genre
391  A Futile and Stupid Gesture  Biographical/Comedy

_____________________________End of group____________________________
Group Name: Biopic
                               Title   Genre
166                            Barry  Biopic
207                      Come Sunday  Biopic
234                           Sergio  Biopic
239  The Most Hated Woman in America  Biopic
245      Baggio: The Divine Ponytail  Biopic
255                  Roxanne Roxanne  Biopic
420                             Mank  Biopic
449                         The Dirt  Biopic
499              Dolemite Is My Name  Biopic

_____________________________End of group____________________________
Group Name: Black comedy
           Title         Genre
123  The Package  Black comedy
126  Bomb Scared  Black comedy

_____________________________End of group____________________________
Group Name: Christian musical
           Title              Genre
141  A Week Away  Christian musical

_____________________________End of group____________________________
Group Name: Christmas comedy
                                  Title             Genre
215  The Christmas Chronicles: Part Two  Christmas comedy

_____________________________End of group____________________________
Group Name: Christmas musical
                                     Title              Genre
68  Dolly Parton's Christmas on the Square  Christmas musical

_____________________________End of group____________________________
Group Name: Christmas/Fantasy/Adventure/Comedy
                        Title                               Genre
448  The Christmas Chronicles  Christmas/Fantasy/Adventure/Comedy

_____________________________End of group____________________________
Group Name: Comedy
                                                Title   Genre
6                                   Leyla Everlasting  Comedy
9                                  Sardar Ka Grandson  Comedy
18                          What Happened to Mr. Cha?  Comedy
22                                         Sextuplets  Comedy
27                                   Seriously Single  Comedy
28              The Misadventures of Hedi and Cokeman  Comedy
29                                   5 Star Christmas  Comedy
33   Porta dos Fundos: The First Temptation of Christ  Comedy
35                                        The Players  Comedy
47                                        Take the 10  Comedy
48                                     The Main Event  Comedy
54                                      Airplane Mode  Comedy
65                                       #REALITYHIGH  Comedy
69                                 Father of the Year  Comedy
72                                   Girlfriend's Day  Comedy
73                  Handsome: A Netflix Mystery Movie  Comedy
74                                    Hubie Halloween  Comedy
75                                              Ibiza  Comedy
77                                       Sandy Wexler  Comedy
83                                        The Week Of  Comedy
85                                     Back to School  Comedy
96                                 Despite Everything  Comedy
103                                             Naked  Comedy
110                                     Get the Grift  Comedy
112                                      House Arrest  Comedy
119                                      Step Sisters  Comedy
124                                     Unicorn Store  Comedy
125                                      Wine Country  Comedy
127                                     Brahman Naman  Comedy
138                                     The Sleepover  Comedy
149                                         Lionheart  Comedy
158                                   The Wrong Missy  Comedy
160                                           Yes Day  Comedy
167                                         Candy Jar  Comedy
184                                   The After Party  Comedy
221                      Between Two Ferns: The Movie  Comedy
229                                       Like Father  Comedy
231                                         Otherhood  Comedy
249                     Have You Ever Seen Fireflies?  Comedy
261                                        Win It All  Comedy
271                                      Get the Goat  Comedy
278               Porta dos Fundos: The Last Hangover  Comedy
327                                        Chopsticks  Comedy
342                      The Incredible Jessica James  Comedy
377                            Just Another Christmas  Comedy
397                              Long Live Brij Mohan  Comedy
399                                     Death to 2020  Comedy
447                                       Rose Island  Comedy
492                           The 40-Year-Old Version  Comedy

_____________________________End of group____________________________
Group Name: Comedy / Musical
                                                 Title             Genre
107                            A Very Murray Christmas  Comedy / Musical
430  The Lonely Island Presents: The Unauthorized B...  Comedy / Musical

_____________________________End of group____________________________
Group Name: Comedy horror
           Title          Genre
150  Little Evil  Comedy horror

_____________________________End of group____________________________
Group Name: Comedy mystery
              Title           Genre
212  Murder Mystery  Comedy mystery

_____________________________End of group____________________________
Group Name: Comedy-drama
                                         Title         Genre
81                                   Tall Girl  Comedy-drama
128                                 Double Dad  Comedy-drama
134                             The Last Laugh  Comedy-drama
161                                     15-Aug  Comedy-drama
176                               Rajma Chawal  Comedy-drama
203                             The Polka King  Comedy-drama
248                     Crazy Awesome Teachers  Comedy-drama
285                             The Laundromat  Comedy-drama
305                         Nappily Ever After  Comedy-drama
311                        The Heartbreak Club  Comedy-drama
385                                   Tallulah  Comedy-drama
423                                   Pagglait  Comedy-drama
431  The Meyerowitz Stories (New and Selected)  Comedy-drama
518                 The Fundamentals of Caring  Comedy-drama

_____________________________End of group____________________________
Group Name: Comedy/Fantasy/Family
                                      Title                  Genre
94  A Babysitter's Guide to Monster Hunting  Comedy/Fantasy/Family

_____________________________End of group____________________________
Group Name: Comedy/Horror
                            Title          Genre
185  The Babysitter: Killer Queen  Comedy/Horror

_____________________________End of group____________________________
Group Name: Coming-of-age comedy-drama
         Title                       Genre
489  Seventeen  Coming-of-age comedy-drama

_____________________________End of group____________________________
Group Name: Concert Film
                                           Title         Genre
293         Ariana Grande: Excuse Me, I Love You  Concert Film
525                Shawn Mendes: Live in Concert  Concert Film
532  Barbra: The Music, The Mem'ries, The Magic!  Concert Film
557       Justin Timberlake + The Tennessee Kids  Concert Film
578   Ben Platt: Live from Radio City Music Hall  Concert Film
579        Taylor Swift: Reputation Stadium Tour  Concert Film

_____________________________End of group____________________________
Group Name: Crime drama
                               Title        Genre
116                          Òlòt?ré  Crime drama
230                       Lost Girls  Crime drama
233                       Rogue City  Crime drama
287                     The Outsider  Crime drama
361             The Crimes That Bind  Crime drama
429                   The Highwaymen  Crime drama
461                            Ferry  Crime drama
491                             Soni  Crime drama
500  El Camino: A Breaking Bad Movie  Crime drama
508                       On My Skin  Crime drama
561                     The Irishman  Crime drama

_____________________________End of group____________________________
Group Name: Crime thriller
            Title           Genre
280  Shimmer Lake  Crime thriller

_____________________________End of group____________________________
Group Name: Dance comedy
       Title         Genre
243  Work It  Dance comedy

_____________________________End of group____________________________
Group Name: Dark comedy
                   Title        Genre
145  El Camino Christmas  Dark comedy
181         Small Crimes  Dark comedy

_____________________________End of group____________________________
Group Name: Documentary
                                           Title        Genre
0                                Enter the Anime  Documentary
10                          Searching for Sheela  Documentary
15                                After the Raid  Documentary
20             Hello Privilege. It's Me, Chelsea  Documentary
30                                   After Maria  Documentary
..                                           ...          ...
576                      Cuba and the Cameraman   Documentary
577                       Dancing with the Birds  Documentary
580  Winter on Fire: Ukraine's Fight for Freedom  Documentary
582    Emicida: AmarElo - It's All For Yesterday  Documentary
583     David Attenborough: A Life on Our Planet  Documentary

[159 rows x 2 columns]

_____________________________End of group____________________________
Group Name: Drama
                          Title  Genre
11                     The Call  Drama
37                Finding Agnes  Drama
41                  The Binding  Drama
53          The Day of the Lord  Drama
56   Love Like the Falling Rain  Drama
..                          ...    ...
549               The Two Popes  Drama
551                  Yeh Ballet  Drama
559                        Roma  Drama
562  The Trial of the Chicago 7  Drama
565              Marriage Story  Drama

[77 rows x 2 columns]

_____________________________End of group____________________________
Group Name: Drama / Short
                 Title          Genre
345  What Did Jack Do?  Drama / Short

_____________________________End of group____________________________
Group Name: Drama-Comedy
         Title         Genre
487  Paddleton  Drama-Comedy

_____________________________End of group____________________________
Group Name: Drama/Horror
     Title         Genre
268  Cargo  Drama/Horror

_____________________________End of group____________________________
Group Name: Family
              Title   Genre
144      Dad Wanted  Family
225  Finding 'Ohana  Family

_____________________________End of group____________________________
Group Name: Family film
            Title        Genre
52   Holiday Rush  Family film
266         Benji  Family film

_____________________________End of group____________________________
Group Name: Family/Christmas musical
                                  Title                     Genre
333  Jingle Jangle: A Christmas Journey  Family/Christmas musical

_____________________________End of group____________________________
Group Name: Family/Comedy-drama
             Title                Genre
270  Feel the Beat  Family/Comedy-drama

_____________________________End of group____________________________
Group Name: Fantasy
                Title    Genre
186  The Claus Family  Fantasy

_____________________________End of group____________________________
Group Name: Heist
         Title  Genre
44  Coin Heist  Heist

_____________________________End of group____________________________
Group Name: Heist film/Thriller
                             Title                Genre
7  The Last Days of American Crime  Heist film/Thriller

_____________________________End of group____________________________
Group Name: Hidden-camera prank comedy
        Title                       Genre
346  Bad Trip  Hidden-camera prank comedy

_____________________________End of group____________________________
Group Name: Historical drama
        Title             Genre
495  The King  Historical drama

_____________________________End of group____________________________
Group Name: Historical-epic
           Title            Genre
422  Outlaw King  Historical-epic

_____________________________End of group____________________________
Group Name: Horror
                                             Title   Genre
31   I Am the Pretty Thing That Lives in the House  Horror
34                                     Rattlesnake  Horror
46              Nobody Sleeps in the Woods Tonight  Horror
59                                         Cadaver  Horror
71                                       Ghost Lab  Horror
90                             Things Heard & Seen  Horror
101                              In the Tall Grass  Horror
146                                            Eli  Horror
348                                        Bulbbul  Horror

_____________________________End of group____________________________
Group Name: Horror anthology
            Title             Genre
16  Ghost Stories  Horror anthology

_____________________________End of group____________________________
Group Name: Horror comedy
                      Title          Genre

Let us also use for loop for the group obtained using 2 columns and see the result. The first group obtained after running the for loop is shown below.

In [25]:
for name, group in grouped_1:
    print("Group Name:", name)
    print(group, '\n')
    print('______________________________________________End of group__________________________________________')

Group Name: ('Action', 'English')
             Title   Genre           Premiere  Runtime  IMDB Score Language
153    Point Blank  Action      July 12, 2019       86         5.7  English
220  6 Underground  Action  December 13, 2019      128         6.1  English
277          Polar  Action   January 25, 2019      118         6.3  English
372     Extraction  Action     April 24, 2020      117         6.7  English

______________________________________________End of group__________________________________________
Group Name: ('Action', 'French')
              Title   Genre        Premiere  Runtime  IMDB Score Language
39       Sentinelle  Action   March 5, 2021       80         4.7   French
50  Earth and Blood  Action  April 17, 2020       80         4.9   French

______________________________________________End of group__________________________________________
Group Name: ('Action', 'Hindi')
   Title   Genre          Premiere  Runtime  IMDB Score Language
5  Drive  Action  November 1, 2019      147         3.5    Hindi

______________________________________________End of group__________________________________________
Group Name: ('Action comedy', 'English')
                                         Title          Genre  \
61                             Coffee & Kareem  Action comedy
155                                The Do-Over  Action comedy
205  True Memoirs of an International Assassin  Action comedy
257                       Spenser Confidential  Action comedy

              Premiere  Runtime  IMDB Score Language
61       April 3, 2020       88         5.1  English
155       May 27, 2016      108         5.7  English
205  November 11, 2016       98         5.9  English
257      March 6, 2020      111         6.2  English

______________________________________________End of group__________________________________________
Group Name: ('Action comedy', 'Malay')
                 Title          Genre         Premiere  Runtime  IMDB Score  \
13  All Because of You  Action comedy  October 1, 2020      101         4.2

   Language
13    Malay

______________________________________________End of group__________________________________________
Group Name: ('Action thriller', 'English')
        Title            Genre          Premiere  Runtime  IMDB Score Language
318  Wheelman  Action thriller  October 20, 2017       82         6.4  English

______________________________________________End of group__________________________________________
Group Name: ('Action-adventure', 'English/Korean')
    Title             Genre       Premiere  Runtime  IMDB Score  \
507  Okja  Action-adventure  June 28, 2017      121         7.3

           Language
507  English/Korean

______________________________________________End of group__________________________________________
Group Name: ('Action-thriller', 'English')
               Title            Genre        Premiere  Runtime  IMDB Score  \
55       How It Ends  Action-thriller   July 13, 2018      113         5.0
315  Triple Frontier  Action-thriller  March 13, 2019      125         6.4

    Language
55   English
315  English

______________________________________________End of group__________________________________________
Group Name: ('Action-thriller', 'Indonesian')
                      Title            Genre          Premiere  Runtime  \
450  The Night Comes for Us  Action-thriller  October 19, 2018      121

     IMDB Score    Language
450         7.0  Indonesian

______________________________________________End of group__________________________________________
Group Name: ('Action/Comedy', 'English')
              Title          Genre        Premiere  Runtime  IMDB Score  \
99  Game Over, Man!  Action/Comedy  March 23, 2018      101         5.4

   Language
99  English

______________________________________________End of group__________________________________________
Group Name: ('Action/Science fiction', 'English')
                Title                   Genre          Premiere  Runtime  \
104  Outside the Wire  Action/Science fiction  January 15, 2021      114

     IMDB Score Language
104         5.4  English

______________________________________________End of group__________________________________________
Group Name: ('Adventure', 'English')
                            Title      Genre          Premiere  Runtime  \
232         Pee-wee's Big Holiday  Adventure    March 18, 2016       89
337  Mowgli: Legend of the Jungle  Adventure  December 7, 2018      104

     IMDB Score Language
232         6.1  English
337         6.5  English

______________________________________________End of group__________________________________________
Group Name: ('Adventure-romance', 'English')
                   Title              Genre          Premiere  Runtime  \
227  Holiday in the Wild  Adventure-romance  November 1, 2019       85

     IMDB Score Language
227         6.1  English

______________________________________________End of group__________________________________________
Group Name: ('Adventure/Comedy', 'English')
                                     Title             Genre      Premiere  \
122  The Legacy of a Whitetail Deer Hunter  Adventure/Comedy  July 6, 2018

     Runtime  IMDB Score Language
122       83         5.5  English

______________________________________________End of group__________________________________________
Group Name: ('Aftershow / Interview', 'English')
                                                 Title                  Genre  \
66   American Factory: A Conversation with the Obamas   Aftershow / Interview
407           The Boys in the Band: Something Personal  Aftershow / Interview
434  I'm No Longer Here: A Discussion with Guillerm...  Aftershow / Interview
439  Ma Rainey's Black Bottom: A Legacy Brought to ...  Aftershow / Interview
451  13th: A Conversation with Oprah Winfrey & Ava ...  Aftershow / Interview
528                      The Irishman: In Conversation  Aftershow / Interview

               Premiere  Runtime  IMDB Score Language
66      August 21, 2019       10         5.2  English
407  September 30, 2020       28         6.8  English
434    November 3, 2020       14         7.0  English
439   December 18, 2020       31         7.0  English
451    January 26, 2017       36         7.1  English
528   November 27, 2019       23         7.4  English

______________________________________________End of group__________________________________________
Group Name: ('Animated musical comedy', 'English')
                      Title                    Genre        Premiere  Runtime  \
366  Arlo the Alligator Boy  Animated musical comedy  April 16, 2021       92

     IMDB Score Language
366         6.7  English

______________________________________________End of group__________________________________________
Group Name: ('Animation', 'English')
                                  Title      Genre           Premiere  \
64               The Larva Island Movie  Animation      July 23, 2020
253  Octonauts & the Caves of Sac Actun  Animation    August 14, 2020
452                  Angela's Christmas  Animation  November 30, 2018
453             Angela's Christmas Wish  Animation   December 1, 2020
506  Octonauts & the Great Barrier Reef  Animation   October 13, 2020

     Runtime  IMDB Score Language
64        90         5.1  English
253       72         6.2  English
452       30         7.1  English
453       47         7.1  English
506       47         7.3  English

______________________________________________End of group__________________________________________
Group Name: ('Animation / Comedy', 'English')
                                 Title               Genre        Premiere  \
446  Rocko's Modern Life: Static Cling  Animation / Comedy  August 9, 2019

     Runtime  IMDB Score Language
446       45         7.0  English

______________________________________________End of group__________________________________________
Group Name: ('Animation / Musicial', 'English')
                                       Title                 Genre  \
309  Sturgill Simpson Presents: Sound & Fury  Animation / Musicial

               Premiere  Runtime  IMDB Score Language
309  September 27, 2019       41         6.4  English

______________________________________________End of group__________________________________________
Group Name: ('Animation / Science Fiction', 'English')
                              Title                        Genre  \
537  Invader Zim: Enter the Florpus  Animation / Science Fiction

            Premiere  Runtime  IMDB Score Language
537  August 16, 2019       71         7.5  English

______________________________________________End of group__________________________________________
Group Name: ('Animation / Short', 'English')
                              Title              Genre           Premiere  \
325                         Canvas   Animation / Short  December 11, 2020
417                Cops and Robbers  Animation / Short  December 28, 2020
513         Sitara: Let Girls Dream  Animation / Short      March 8, 2020
560  If Anything Happens I Love You  Animation / Short  November 20, 2020

     Runtime  IMDB Score Language
325        9         6.5  English
417        7         6.9  English
513       15         7.3  English
560       12         7.8  English

______________________________________________End of group__________________________________________
Group Name: ('Animation/Christmas/Comedy/Adventure', 'English')
     Title                                 Genre           Premiere  Runtime  \
573  Klaus  Animation/Christmas/Comedy/Adventure  November 15, 2019       97

     IMDB Score Language
573         8.2  English

______________________________________________End of group__________________________________________
Group Name: ('Animation/Comedy/Adventure', 'English')
               Title                       Genre        Premiere  Runtime  \
314  The Willoughbys  Animation/Comedy/Adventure  April 22, 2020       90

     IMDB Score Language
314         6.4  English

______________________________________________End of group__________________________________________
Group Name: ('Animation/Musical/Adventure', 'English')
             Title                        Genre          Premiere  Runtime  \
306  Over the Moon  Animation/Musical/Adventure  October 23, 2020       95

     IMDB Score Language
306         6.4  English

______________________________________________End of group__________________________________________
Group Name: ('Animation/Superhero', 'English')
       Title                Genre         Premiere  Runtime  IMDB Score  \
51  Fearless  Animation/Superhero  August 14, 2020       89         4.9

   Language
51  English

______________________________________________End of group__________________________________________
Group Name: ('Anime / Short', 'English')
          Title          Genre       Premiere  Runtime  IMDB Score Language
40  Sol Levante  Anime / Short  April 2, 2020        4         4.7  English

______________________________________________End of group__________________________________________
Group Name: ('Anime/Fantasy', 'Japanese')
              Title          Genre       Premiere  Runtime  IMDB Score  \
364  A Whisker Away  Anime/Fantasy  June 18, 2020      104         6.7

     Language
364  Japanese

______________________________________________End of group__________________________________________
Group Name: ('Anime/Science fiction', 'Japanese')
                         Title                  Genre        Premiere  \
323  Altered Carbon: Resleeved  Anime/Science fiction  March 19, 2020
368                     Blame!  Anime/Science fiction    May 20, 2017

     Runtime  IMDB Score  Language
323       74         6.5  Japanese
368      106         6.7  Japanese

______________________________________________End of group__________________________________________
Group Name: ('Anthology/Dark comedy', 'Hindi')
    Title                  Genre           Premiere  Runtime  IMDB Score  \
543  Ludo  Anthology/Dark comedy  November 12, 2020      149         7.6

    Language
543    Hindi

______________________________________________End of group__________________________________________
Group Name: ('Biographical/Comedy', 'English')
                           Title                Genre          Premiere  \
391  A Futile and Stupid Gesture  Biographical/Comedy  January 26, 2018

     Runtime  IMDB Score Language
391      101         6.8  English

______________________________________________End of group__________________________________________
Group Name: ('Biopic', 'English')
                               Title   Genre           Premiere  Runtime  \
166                            Barry  Biopic  December 16, 2016      104
207                      Come Sunday  Biopic     April 13, 2018      106
234                           Sergio  Biopic     April 17, 2020      118
239  The Most Hated Woman in America  Biopic     March 24, 2017       92
255                  Roxanne Roxanne  Biopic     March 23, 2018       98
420                             Mank  Biopic   December 4, 2020      132
449                         The Dirt  Biopic     March 22, 2019      108
499              Dolemite Is My Name  Biopic   October 25, 2019      118

     IMDB Score Language
166         5.8  English
207         6.0  English
234         6.1  English
239         6.1  English
255         6.2  English
420         6.9  English
449         7.0  English
499         7.3  English

______________________________________________End of group__________________________________________
Group Name: ('Biopic', 'Italian')
                           Title   Genre      Premiere  Runtime  IMDB Score  \
245  Baggio: The Divine Ponytail  Biopic  May 26, 2021       92         6.2

    Language
245  Italian

______________________________________________End of group__________________________________________
Group Name: ('Black comedy', 'English')
           Title         Genre         Premiere  Runtime  IMDB Score Language
123  The Package  Black comedy  August 10, 2018       94         5.5  English

______________________________________________End of group__________________________________________
Group Name: ('Black comedy', 'Spanish/Basque')
           Title         Genre          Premiere  Runtime  IMDB Score  \
126  Bomb Scared  Black comedy  October 12, 2017       89         5.6

           Language
126  Spanish/Basque

______________________________________________End of group__________________________________________
Group Name: ('Christian musical', 'English')
           Title              Genre        Premiere  Runtime  IMDB Score  \
141  A Week Away  Christian musical  March 26, 2021       97         5.7

    Language
141  English

______________________________________________End of group__________________________________________
Group Name: ('Christmas comedy', 'English')
                                  Title             Genre           Premiere  \
215  The Christmas Chronicles: Part Two  Christmas comedy  November 25, 2020

     Runtime  IMDB Score Language
215      115         6.0  English

______________________________________________End of group__________________________________________
Group Name: ('Christmas musical', 'English')
                                     Title              Genre  \
68  Dolly Parton's Christmas on the Square  Christmas musical

             Premiere  Runtime  IMDB Score Language
68  November 22, 2020       98         5.2  English

______________________________________________End of group__________________________________________
Group Name: ('Christmas/Fantasy/Adventure/Comedy', 'English')
                        Title                               Genre  \
448  The Christmas Chronicles  Christmas/Fantasy/Adventure/Comedy

              Premiere  Runtime  IMDB Score Language
448  November 22, 2018      104         7.0  English

______________________________________________End of group__________________________________________
Group Name: ('Comedy', 'English')
                                 Title   Genre            Premiere  Runtime  \
22                          Sextuplets  Comedy     August 16, 2019       99
27                    Seriously Single  Comedy       July 31, 2020      107
47                         Take the 10  Comedy    January 20, 2017       80
48                      The Main Event  Comedy      April 10, 2020      101
65                        #REALITYHIGH  Comedy   September 8, 2017       99
69                  Father of the Year  Comedy       July 20, 2018       94
72                    Girlfriend's Day  Comedy   February 14, 2017       70
73   Handsome: A Netflix Mystery Movie  Comedy         May 5, 2017       81
74                     Hubie Halloween  Comedy     October 7, 2020      103
75                               Ibiza  Comedy        May 25, 2018       94
77                        Sandy Wexler  Comedy      April 14, 2017      131
83                         The Week Of  Comedy      April 27, 2018      116
103                              Naked  Comedy     August 11, 2017       96
119                       Step Sisters  Comedy    January 19, 2018      108
124                      Unicorn Store  Comedy       April 5, 2019       92
125                       Wine Country  Comedy        May 10, 2019      103
127                      Brahman Naman  Comedy        July 7, 2016       95
138                      The Sleepover  Comedy     August 21, 2020      103
149                          Lionheart  Comedy     January 4, 2019       94
158                    The Wrong Missy  Comedy        May 13, 2020       90
160                            Yes Day  Comedy      March 12, 2021       86
167                          Candy Jar  Comedy      April 27, 2018       92
184                    The After Party  Comedy     August 24, 2018       89
221       Between Two Ferns: The Movie  Comedy  September 20, 2019       82
229                        Like Father  Comedy      August 3, 2018      103
231                          Otherhood  Comedy      August 2, 2019      100
261                         Win It All  Comedy       April 7, 2017       88
342       The Incredible Jessica James  Comedy       July 28, 2017       83
399                      Death to 2020  Comedy   December 27, 2020       70
492            The 40-Year-Old Version  Comedy     October 9, 2020      124

     IMDB Score Language
22          4.4  English
27          4.5  English
47          4.8  English
48          4.8  English
65          5.2  English
69          5.2  English
72          5.2  English
73          5.2  English
74          5.2  English
75          5.2  English
77          5.2  English
83          5.2  English
103         5.4  English
119         5.5  English
124         5.5  English
125         5.5  English
127         5.6  English
138         5.6  English
149         5.7  English
158         5.7  English
160         5.7  English
167         5.8  English
184         5.8  English
221         6.1  English
229         6.1  English
231         6.1  English
261         6.2  English
342         6.5  English
399         6.8  English
492         7.2  English

______________________________________________End of group__________________________________________
Group Name: ('Comedy', 'French')
                                    Title   Genre           Premiere  Runtime  \
28  The Misadventures of Hedi and Cokeman  Comedy  February 10, 2021       99
85                         Back to School  Comedy    August 30, 2019       83

    IMDB Score Language
28         4.5   French
85         5.3   French

______________________________________________End of group__________________________________________
Group Name: ('Comedy', 'Hindi')
                    Title   Genre           Premiere  Runtime  IMDB Score  \
9      Sardar Ka Grandson  Comedy       May 18, 2021      139         4.1

You can also see the first entry in each group by using .first().

In [26]:
grouped.first()

,Title,Premiere,Runtime,IMDB Score,Language
Genre,,,,,
Action,Drive,"November 1, 2019",147,3.5,Hindi
Action comedy,All Because of You,"October 1, 2020",101,4.2,Malay
Action thriller,Wheelman,"October 20, 2017",82,6.4,English
Action-adventure,Okja,"June 28, 2017",121,7.3,English/Korean
Action-thriller,How It Ends,"July 13, 2018",113,5.0,English
...,...,...,...,...,...
War,Sand Castle,"April 21, 2017",113,6.3,English
War drama,Da 5 Bloods,"June 12, 2020",155,6.5,English
War-Comedy,War Machine,"May 26, 2017",122,6.0,English
Western,The Ridiculous 6,"December 11, 2015",119,4.8,English
Zombie/Heist,Army of the Dead,"May 21, 2021",148,5.9,English

Similarly, last entry in each group can be obtained using .last()

In [27]:
grouped.last()

,Title,Premiere,Runtime,IMDB Score,Language
Genre,,,,,
Action,Extraction,"April 24, 2020",117,6.7,English
Action comedy,Spenser Confidential,"March 6, 2020",111,6.2,English
Action thriller,Wheelman,"October 20, 2017",82,6.4,English
Action-adventure,Okja,"June 28, 2017",121,7.3,English/Korean
Action-thriller,The Night Comes for Us,"October 19, 2018",121,7.0,Indonesian
...,...,...,...,...,...
War,The Siege of Jadotville,"October 7, 2016",108,7.2,English
War drama,Beasts of No Nation,"October 16, 2015",136,7.7,English/Akan
War-Comedy,War Machine,"May 26, 2017",122,6.0,English
Western,The Ballad of Buster Scruggs,"November 16, 2018",132,7.3,English
Zombie/Heist,Army of the Dead,"May 21, 2021",148,5.9,English

If you want to see the Nth entry in each group, you can use the .nth() function. The code shown below outputs the entry at row index 2.

In [29]:
grouped.nth(2)

,Title,Premiere,Runtime,IMDB Score,Language
Genre,,,,,
Action,Earth and Blood,"April 17, 2020",80,4.9,French
Action comedy,The Do-Over,"May 27, 2016",108,5.7,English
Action-thriller,The Night Comes for Us,"October 19, 2018",121,7.0,Indonesian
Aftershow / Interview,I'm No Longer Here: A Discussion with Guillerm...,"November 3, 2020",14,7.0,English
Animation,Angela's Christmas,"November 30, 2018",30,7.1,English
Animation / Short,Sitara: Let Girls Dream,"March 8, 2020",15,7.3,English
Biopic,Sergio,"April 17, 2020",118,6.1,English
Comedy,What Happened to Mr. Cha?,"January 1, 2021",102,4.3,Korean
Comedy-drama,The Last Laugh,"January 11, 2019",98,5.6,English
Concert Film,"Barbra: The Music, The Mem'ries, The Magic!","November 22, 2017",108,7.5,English
Crime drama,Rogue City,"October 30, 2020",116,6.1,French
Documentary,After the Raid,"December 19, 2019",25,4.3,Spanish
Drama,The Binding,"October 2, 2020",93,4.7,Italian
Horror,Nobody Sleeps in the Woods Tonight,"October 28, 2020",103,4.8,Polish
Horror thriller,Gerald's Game,"September 29, 2017",103,6.5,English
One-man show,Springsteen on Broadway,"December 16, 2018",153,8.5,English
Psychological thriller,I'm Thinking of Ending Things,"September 4, 2020",134,6.6,English
Romance,Tramps,"April 21, 2017",83,6.5,English
Romantic comedy,Squared Love,"February 11, 2021",102,5.0,Polish
Romantic drama,Christmas Inheritance,"December 15, 2017",104,5.7,English
Science fiction,The Midnight Sky,"December 23, 2020",118,5.6,English
Science fiction/Drama,The Discovery,"March 31, 2017",102,6.3,English
Science fiction/Thriller,iBoy,"January 27, 2017",90,6.0,English
Sports-drama,First Match,"March 30, 2018",102,6.4,English
Thriller,Secret Obsession,"July 18, 2019",97,4.4,English
Variety show,Sarah Cooper: Everything's Fine,"October 27, 2020",49,5.6,English
Western,The Ballad of Buster Scruggs,"November 16, 2018",132,7.3,English

Let us now see the first entry in grouped_1.

In [30]:
grouped_1.first()

                                          Title           Premiere  Runtime  \
Genre         Language
Action        English               Point Blank      July 12, 2019       86
              French                 Sentinelle      March 5, 2021       80
              Hindi                       Drive   November 1, 2019      147
Action comedy English           Coffee & Kareem      April 3, 2020       88
              Malay          All Because of You    October 1, 2020      101
...                                         ...                ...      ...
War drama     English/Akan  Beasts of No Nation   October 16, 2015      136
War-Comedy    English               War Machine       May 26, 2017      122
Western       English          The Ridiculous 6  December 11, 2015      119
              Portuguese             The Killer  November 10, 2017       99
Zombie/Heist  English          Army of the Dead       May 21, 2021      148

                            IMDB Score
Genre         Language
Action        English              5.7
              French               4.7
              Hindi                3.5
Action comedy English              5.1
              Malay                4.2
...                                ...
War drama     English/Akan         7.7
War-Comedy    English              6.0
Western       English              4.8
              Portuguese           6.1
Zombie/Heist  English              5.9

[204 rows x 4 columns]

# 1.7  Sorting when using groupby

As we have seen earlier, groups are listed in alphabetical order from A to Z. If sort is set to ‘False’,then no ordering will take place when forming groups. This can be seen in the below cells.

In [32]:
grouped_2 = movies_info.groupby('Genre', sort = False)

You can see the result of grouping using .groups. Notice how the group names are arranged in order of appearance in the dataset.

In [33]:
grouped_2.groups

{'Documentary': [0, 10, 15, 20, 30, 36, 80, 111, 140, 151, 152, 199, 202, 223, 228, 259, 260, 263, 275, 286, 290, 292, 295, 301, 303, 304, 308, 310, 312, 316, 320, 324, 326, 329, 334, 339, 351, 353, 355, 356, 357, 359, 363, 367, 370, 371, 373, 375, 378, 384, 387, 392, 393, 394, 396, 400, 401, 402, 403, 404, 410, 412, 414, 415, 416, 419, 424, 425, 426, 427, 432, 433, 435, 436, 437, 440, 441, 442, 443, 444, 445, 455, 456, 458, 459, 460, 462, 463, 464, 465, 466, 468, 469, 471, 472, 473, 476, 479, 480, 482, ...], 'Thriller': [1, 14, 21, 23, 25, 43, 45, 57, 60, 86, 88, 89, 100, 109, 117, 130, 137, 154, 159, 172, 192, 201, 242, 251, 252, 254, 288, 298, 313, 332, 398, 413, 509], 'Science fiction/Drama': [2, 38, 283], 'Horror thriller': [3, 19, 331], 'Mystery': [4, 196], 'Action': [5, 39, 50, 153, 220, 277, 372], 'Comedy': [6, 9, 18, 22, 27, 28, 29, 33, 35, 47, 48, 54, 65, 69, 72, 73, 74, 75, 77, 83, 85, 96, 103, 110, 112, 119, 124, 125, 127, 138, 149, 158, 160, 167, 184, 221, 229, 231, 249, 261, 271, 278, 327, 342, 377, 397, 399, 447, 492], 'Heist film/Thriller': [7], 'Musical/Western/Fantasy': [8], 'Drama': [11, 37, 41, 53, 56, 70, 82, 87, 92, 93, 97, 102, 148, 164, 165, 168, 169, 189, 191, 198, 208, 210, 211, 222, 224, 235, 236, 241, 246, 247, 258, 269, 273, 274, 276, 284, 291, 299, 307, 317, 322, 335, 336, 338, 343, 354, 365, 369, 374, 376, 381, 382, 383, 388, 389, 390, 405, 406, 408, 409, 411, 418, 438, 454, 470, 475, 477, 481, 488, 490, 493, 504, 549, 551, 559, 562, 565], 'Romantic comedy': [12, 26, 58, 67, 84, 91, 95, 105, 114, 121, 129, 131, 147, 156, 162, 163, 171, 173, 175, 177, 187, 188, 190, 200, 216, 217, 218, 238, 256, 264, 272, 289, 300, 319, 341, 349, 395, 478, 486], 'Action comedy': [13, 61, 155, 205, 257], 'Horror anthology': [16], 'Political thriller': [17], 'Superhero-Comedy': [24], 'Horror': [31, 34, 46, 59, 71, 90, 101, 146, 348], 'Romance drama': [32], 'Anime / Short': [40], 'Superhero': [42, 213], 'Heist': [44], 'Western': [49, 237, 516], 'Animation/Superhero': [51], 'Family film': [52, 266], 'Action-thriller': [55, 315, 450], 'Teen comedy-drama': [62], 'Romantic drama': [63, 135, 143, 302, 379], 'Animation': [64, 253, 452, 453, 506], 'Aftershow / Interview': [66, 407, 434, 439, 451, 528], 'Christmas musical': [68], 'Science fiction adventure': [76], 'Science fiction': [78, 120, 136, 358], 'Variety show': [79, 113, 133, 539], 'Comedy-drama': [81, 128, 134, 161, 176, 203, 248, 285, 305, 311, 385, 423, 431, 518], 'Comedy/Fantasy/Family': [94], 'Supernatural drama': [98], 'Action/Comedy': [99], 'Action/Science fiction': [104], 'Romantic teenage drama': [106], 'Comedy / Musical': [107, 430], 'Musical': [108, 204], 'Science fiction/Mystery': [115], 'Crime drama': [116, 230, 233, 287, 361, 429, 461, 491, 500, 508, 561], 'Psychological thriller drama': [118], 'Adventure/Comedy': [122], 'Black comedy': [123, 126], 'Romance': [132, 321, 344, 350, 421, 428], 'Horror comedy': [139], 'Christian musical': [141], 'Romantic teen drama': [142], 'Family': [144, 225], 'Dark comedy': [145, 181], 'Comedy horror': [150], 'Psychological thriller': [157, 347, 352, 474], 'Biopic': [166, 207, 234, 239, 245, 255, 420, 449, 499], 'Science fiction/Thriller': [170, 183, 209, 294], 'Mockumentary': [174, 197], 'Satire': [178, 182], 'One-man show': [179, 467, 581], 'Romantic comedy-drama': [180], 'Comedy/Horror': [185], 'Fantasy': [186], 'Sports-drama': [193, 250, 297], 'Zombie/Heist': [194], 'Psychological horror': [195], 'Sports film': [206], 'Comedy mystery': [212], 'Romantic thriller': [214], 'Christmas comedy': [215], 'War-Comedy': [219], 'Romantic comedy/Holiday': [226], 'Adventure-romance': [227], 'Adventure': [232, 337], 'Horror-thriller': [240, 265], 'Dance comedy': [243], 'Stop Motion': [244], 'Horror/Crime drama': [262], 'Urban fantasy': [267], 'Drama/Horror': [268], 'Family/Comedy-drama': [270], 'War': [279, 497], 'Crime thriller': [280], 'Science fiction/Action': [281], 'Teen comedy horror': [282], 'Concert Film': [293, 525, 532, 557, 578, 579], 'Musical comedy': [296, 330], 'Animation/Musical/Adventure': [306], 'Animation / Musicial': [309], 'Animation/Comedy/Adventure': [314], 'Action thriller': [318], 'Anime/Science fiction': [323, 368], 'Animation / Short': [325, 417, 513, 560], 'War drama': [328, 553], 'Family/Christmas musical': [333], 'Science fiction thriller': [340], 'Drama / Short': [345], 'Hidden-camera prank comedy': [346], 'Spy thriller': [360, 362], 'Anime/Fantasy': [364], 'Animated musical comedy': [366], 'Variety Show': [380], ...}

# 1.8  Apply

After splitting the data, the next step is to apply functions to the groups so formed. These function scan be applied in various ways as can be seen in the below cells.

# 1.8.1  User defined functions

Find out the average Runtime for each genre of movies.

In [35]:
movies_info.groupby('Genre')[['Runtime']].mean()

                     Runtime
Genre
Action            108.000000
Action comedy     101.200000
Action thriller    82.000000
Action-adventure  121.000000
Action-thriller   119.666667
...                      ...
War               110.500000
War drama         145.500000
War-Comedy        122.000000
Western           116.666667
Zombie/Heist      148.000000

[115 rows x 1 columns]

Find out the size of each group after grouping.

In [36]:
movies_info.groupby(['Genre','Language']).size()

Genre          Language
Action         English         4
               French          2
               Hindi           1
Action comedy  English         4
               Malay           1
                              ..
War drama      English/Akan    1
War-Comedy     English         1
Western        English         2
               Portuguese      1
Zombie/Heist   English         1
Length: 204, dtype: int64

Find the minimum Score for each genre

In [37]:
movies_info.groupby('Genre')[['IMDB Score']].min()

                  IMDB Score
Genre
Action                   3.5
Action comedy            4.2
Action thriller          6.4
Action-adventure         7.3
Action-thriller          5.0
...                      ...
War                      6.3
War drama                6.5
War-Comedy               6.0
Western                  4.8
Zombie/Heist             5.9

[115 rows x 1 columns]

Find the number of movies in each language in the dataset

In [38]:
movies_info.groupby('Language').size()

Language
Bengali                         1
Dutch                           3
English                       401
English/Akan                    1
English/Arabic                  1
English/Hindi                   2
English/Japanese                2
English/Korean                  1
English/Mandarin                2
English/Russian                 1
English/Spanish                 5
English/Swedish                 1
English/Taiwanese/Mandarin      1
English/Ukranian/Russian        1
Filipino                        2
French                         20
Georgian                        1
German                          5
Hindi                          33
Indonesian                      9
Italian                        14
Japanese                        6
Khmer/English/French            1
Korean                          6
Malay                           1
Marathi                         3
Norwegian                       1
Polish                          3
Portuguese                     12
Spanish                        31
Spanish/Basque                  1
Spanish/Catalan                 1
Spanish/English                 1
Swedish                         1
Tamil                           1
Thai                            2
Thia/English                    1
Turkish                         5
dtype: int64

# 1.8.2  Working with apply()

apply() can be used to apply an operation to the groups. Some examples have been shown below.

Find the maximum Runtime for each genre using lambda function .Lambda function finds the maximum in each group formed by groupby().

In [41]:
movies_info.groupby('Genre')[['Runtime']].apply(lambda gr:gr.max())

                  Runtime
Genre
Action                147
Action comedy         111
Action thriller        82
Action-adventure      121
Action-thriller       125
...                   ...
War                   113
War drama             155
War-Comedy            122
Western               132
Zombie/Heist          148

[115 rows x 1 columns]

Find the maximum Runtime for each genre using the inbuilt function.

In [42]:
movies_info.groupby('Genre')[['Runtime']].apply(max)

                  Runtime
Genre
Action                147
Action comedy         111
Action thriller        82
Action-adventure      121
Action-thriller       125
...                   ...
War                   113
War drama             155
War-Comedy            122
Western               132
Zombie/Heist          148

[115 rows x 1 columns]

Find the maximum Runtime and IMDB Score for each genre using the user defined function.

In [44]:
def find_max(df):
    return df.max()

movies_info.groupby('Genre')[['Runtime', 'IMDB Score']].apply(find_max)

                  Runtime  IMDB Score
Genre
Action              147.0         6.7
Action comedy       111.0         6.2
Action thriller      82.0         6.4
Action-adventure    121.0         7.3
Action-thriller     125.0         7.0
...                   ...         ...
War                 113.0         7.2
War drama           155.0         7.7
War-Comedy          122.0         6.0
Western             132.0         7.3
Zombie/Heist        148.0         5.9

[115 rows x 2 columns]

# 1.8.3  Aggregation

agg() can be used to find summary statistics about the data such as count, minimum, maximumand mean in a single step.

Find out the count, minimum, maximum and average of the IMDB Score for eachgenre.

In [45]:
movies_info.groupby('Genre')['IMDB Score'].agg(['count','min','max','mean'])

                  count  min  max      mean
Genre
Action                7  3.5  6.7  5.414286
Action comedy         5  4.2  6.2  5.420000
Action thriller       1  6.4  6.4  6.400000
Action-adventure      1  7.3  7.3  7.300000
Action-thriller       3  5.0  7.0  6.133333
...                 ...  ...  ...       ...
War                   2  6.3  7.2  6.750000
War drama             2  6.5  7.7  7.100000
War-Comedy            1  6.0  6.0  6.000000
Western               3  4.8  7.3  6.066667
Zombie/Heist          1  5.9  5.9  5.900000

[115 rows x 4 columns]

Find out the minimum and maximum duration and minimum and maximum ratings for each genre

In [46]:
movies_info.groupby('Genre').agg({'Runtime': ['max','min'],'IMDB Score': ['mean','max']})

                 Runtime      IMDB Score
                     max  min       mean  max
Genre
Action               147   80   5.414286  6.7
Action comedy        111   88   5.420000  6.2
Action thriller       82   82   6.400000  6.4
Action-adventure     121  121   7.300000  7.3
Action-thriller      125  113   6.133333  7.0
...                  ...  ...        ...  ...
War                  113  108   6.750000  7.2
War drama            155  136   7.100000  7.7
War-Comedy           122  122   6.000000  6.0
Western              132   99   6.066667  7.3
Zombie/Heist         148  148   5.900000  5.9

[115 rows x 4 columns]

Find out the average runtime and the maximum IMDB Score for each language

In [48]:
movies_info.groupby('Language').agg({'Runtime':'mean','IMDB Score':'max'})

                               Runtime  IMDB Score
Language
Bengali                      41.000000         7.1
Dutch                        99.666667         7.1
English                      91.817955         9.0
English/Akan                136.000000         7.7
English/Arabic              114.000000         7.3
English/Hindi                32.500000         7.4
English/Japanese             89.000000         6.3
English/Korean              121.000000         7.3
English/Mandarin             59.000000         7.3
English/Russian              90.000000         7.3
English/Spanish              39.200000         7.3
English/Swedish              40.000000         6.5
English/Taiwanese/Mandarin   91.000000         6.5
English/Ukranian/Russian     91.000000         8.4
Filipino                     99.500000         5.5
French                       92.700000         6.9
Georgian                     23.000000         6.8
German                       99.600000         6.4
Hindi                       115.787879         7.6
Indonesian                  103.777778         7.0
Italian                      98.357143         7.3
Japanese                     99.333333         6.7
Khmer/English/French        136.000000         7.2
Korean                      115.833333         7.5
Malay                       101.000000         4.2
Marathi                     121.666667         7.2
Norwegian                    86.000000         5.1
Polish                       98.666667         5.7
Portuguese                   91.250000         8.6
Spanish                      93.387097         8.2
Spanish/Basque               89.000000         5.6
Spanish/Catalan             116.000000         6.4
Spanish/English              96.000000         7.3
Swedish                      86.000000         5.5
Tamil                       101.000000         7.2
Thai                        101.000000         5.7
Thia/English                 80.000000         6.7
Turkish                     101.800000         6.7

From this you can see that Hindi language movies have the longest Runtime and also the highest IMDB Score.

# 1.9  Transformation

While apply stage includes applying some function to the grouped data to find an overall summary for the group, transformation includes applying a function to each element in the group to modify it. For example, the Runtime is given in minutes and we can transform it to hours by dividing each value by 60. .transform can be used to perform such operations on the grouped data as shown below.

A new column is added to the DataFrame to hold the transformed values.

In [52]:
movies_info['Runtime_hrs']= movies_info.groupby('Genre')['Runtime'].transform(lambda x:x/60)

In [53]:
movies_info.head()

,Title,Genre,Premiere,Runtime,IMDB Score,Language,Runtime_hrs
0,Enter the Anime,Documentary,"August 5, 2019",58,2.5,English/Japanese,0.966667
1,Dark Forces,Thriller,"August 21, 2020",81,2.6,Spanish,1.350000
2,The App,Science fiction/Drama,"December 26, 2019",79,2.6,Italian,1.316667
3,The Open House,Horror thriller,"January 19, 2018",94,3.2,English,1.566667
4,Kaali Khuhi,Mystery,"October 30, 2020",90,3.4,Hindi,1.500000

Let us now replace the IMDB Score in each genre by the genre’s mean IMDB Score.

In [54]:
movies_info['IMDB Score adj'] = movies_info.groupby('Genre')['IMDB Score'].transform(lambda x:x.mean())

In [55]:
movies_info.head()

,Title,Genre,Premiere,Runtime,IMDB Score,Language,Runtime_hrs,IMDB Score adj
0,Enter the Anime,Documentary,"August 5, 2019",58,2.5,English/Japanese,0.966667,6.936478
1,Dark Forces,Thriller,"August 21, 2020",81,2.6,Spanish,1.350000,5.563636
2,The App,Science fiction/Drama,"December 26, 2019",79,2.6,Italian,1.316667,4.533333
3,The Open House,Horror thriller,"January 19, 2018",94,3.2,English,1.566667,4.700000
4,Kaali Khuhi,Mystery,"October 30, 2020",90,3.4,Hindi,1.500000,4.650000

# 1.10  Filter

After grouping the data, groups can be filtered by using some condition. For example, in the belowcell, Genre with a average IMDB Score higher than 4 have been filtered using .filter(

In [56]:
movies_info.groupby('Genre').filter(lambda x:x['IMDB Score'].mean()>=4)

,Title,Genre,Premiere,Runtime,IMDB Score,Language,Runtime_hrs,IMDB Score adj
0,Enter the Anime,Documentary,"August 5, 2019",58,2.5,English/Japanese,0.966667,6.936478
1,Dark Forces,Thriller,"August 21, 2020",81,2.6,Spanish,1.350000,5.563636
2,The App,Science fiction/Drama,"December 26, 2019",79,2.6,Italian,1.316667,4.533333
3,The Open House,Horror thriller,"January 19, 2018",94,3.2,English,1.566667,4.700000
4,Kaali Khuhi,Mystery,"October 30, 2020",90,3.4,Hindi,1.500000,4.650000
...,...,...,...,...,...,...,...,...
579,Taylor Swift: Reputation Stadium Tour,Concert Film,"December 31, 2018",125,8.4,English,2.083333,7.633333
580,Winter on Fire: Ukraine's Fight for Freedom,Documentary,"October 9, 2015",91,8.4,English/Ukranian/Russian,1.516667,6.936478
581,Springsteen on Broadway,One-man show,"December 16, 2018",153,8.5,English,2.550000,7.133333
582,Emicida: AmarElo - It's All For Yesterday,Documentary,"December 8, 2020",89,8.6,Portuguese,1.483333,6.936478
583,David Attenborough: A Life on Our Planet,Documentary,"October 4, 2020",83,9.0,English,1.383333,6.936478

# 1.11  Combine

In the final stage, let us see how the results of applying different operations to the grouped data are combined into a DataFrame. This is done automatically in most cases. For example, using agg() returns the summary of the data in the form of a DataFrame.

In [60]:
movies_combine = movies_info.groupby('Genre').agg({'Runtime': ['max','min'],'IMDB Score':['mean','max']})

In [58]:
type(movies_combine)

pandas.core.frame.DataFrame

You can further use this DataFrame for various purposes.

In [63]:
movies_combine.head()

                 Runtime      IMDB Score
                     max  min       mean  max
Genre
Action               147   80   5.414286  6.7
Action comedy        111   88   5.420000  6.2
Action thriller       82   82   6.400000  6.4
Action-adventure     121  121   7.300000  7.3
Action-thriller      125  113   6.133333  7.0

You can also create a DataFrame as shown below. The below cell summarises all the three stages:

•Split:movies_info.groupby(‘Genre’)

•Apply:movies_info.groupby(‘Genre’).size()

•Combine:pd.DataFrame(movies_info.groupby(‘Genre’).size(), columns= [‘Number’]

In [65]:
pd.DataFrame(movies_info.groupby('Genre').size(),columns = ['Number'])

                  Number
Genre
Action                 7
Action comedy          5
Action thriller        1
Action-adventure       1
Action-thriller        3
...                  ...
War                    2
War drama              2
War-Comedy             1
Western                3
Zombie/Heist           1

[115 rows x 1 columns]